[ggcm] test_mrc_fld_io: properly run double/float aos tests
Since "double_aos" and "float_aos" don't exist anymore,
this obviously failed now. So instead, use the new "aos"
flag in these tests.

They still fail, as the data read back apparently doesn't
match the data written, so more work remains.

diff --git a/tests/templates/mrc_fld_io_checks.in b/tests/templates/mrc_fld_io_checks.in
--- a/tests/templates/mrc_fld_io_checks.in
+++ b/tests/templates/mrc_fld_io_checks.in
@@ -1,32 +1,31 @@
 ESTATUS=0
-for fldtype in "float" "double" "int"
-do
-    for nproc in 1 2
-    do
-	echo "Testing ${fldtype} with ${nproc} procs"
-	@MPIRUN@ -n ${nproc} ./test_mrc_fld_io --mrc_fld_type ${fldtype} --mrc_domain_npx ${nproc} \
-	    --mrc_io_type ${IOTYPE}
-	teststatus=$?
-	if test $teststatus -ne 0
-	then
-	    echo "XXX failed XXX"
-	    ESTATUS=${teststatus}
-	else
-	    echo "OOO passed OOO"
-	fi
-
-	echo "Testing ${fldtype} with ${nproc} procs and no component names"
-	@MPIRUN@ -n ${nproc} ./test_mrc_fld_io --mrc_fld_type ${fldtype} --mrc_domain_npx ${nproc} \
-	    --mrc_io_type ${IOTYPE} --nameless 1
-	teststatus=$?
-	if test $teststatus -ne 0
-	then
-	    echo "XXX failed XXX"
-	    ESTATUS=${teststatus}
-	else
-	    echo "OOO passed OOO"
-	fi
-	
+for fldtype in "float" "double" "int"; do
+    for aos in false true; do
+	for nproc in 1 2; do
+	    echo "Testing ${fldtype} with ${nproc} procs"
+	    @MPIRUN@ -n ${nproc} ./test_mrc_fld_io --mrc_fld_type ${fldtype} --mrc_fld_aos ${aos} \
+		   --mrc_domain_npx ${nproc} --mrc_io_type ${IOTYPE}
+	    teststatus=$?
+	    if test $teststatus -ne 0
+	    then
+		echo "XXX failed XXX"
+		ESTATUS=${teststatus}
+	    else
+		echo "OOO passed OOO"
+	    fi
+	    
+	    echo "Testing ${fldtype} with ${nproc} procs and no component names"
+	    @MPIRUN@ -n ${nproc} ./test_mrc_fld_io --mrc_fld_type ${fldtype} --mrc_fld_aos ${aos} \
+		   --mrc_domain_npx ${nproc} --mrc_io_type ${IOTYPE} --nameless 1
+	    teststatus=$?
+	    if test $teststatus -ne 0
+	    then
+		echo "XXX failed XXX"
+		ESTATUS=${teststatus}
+	    else
+		echo "OOO passed OOO"
+	    fi
+	done
     done
 done
 
